### ISSUE TITLE
Page sections

### ISSUE THREAD

**Issue by ghost** [bradrgall/prj-rev-bwfs-dasmoto#2]
https://github.com/bradrgall/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L10-L13

Instead of wrapping a `div` around a single heading element, consider wrapping a `div` around each entire section instead so that you can properly divide the page into sections. 

Then, give each `div` the class `product` (for example) instead since there are three equivalent product sections . You can give the ID to the `h2` tag in each section since those are the only ones that need to be handled uniquely. This will help you write more descriptive and concise CSS selectors. 

```html
<div class="product">
  <h3 id="brushes">Brushes</h3>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg" />
  <h5>Hacksaw Brushes</h5>
  <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <font color="blue"><strong>Starting at $3.00 / brush.</strong></font></p>
</div>
```

**Comment by bradrgall** [comment]
OK, I understand.
