### ISSUE TITLE
Price

### ISSUE THREAD

**Issue by ghost** [bradrgall/prj-rev-bwfs-dasmoto#3]
https://github.com/bradrgall/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L13

Do not use the font tag, which is considered obsolete, nor any inline styles.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font

Just leave the `strong` tag instead and apply styles to it via the CSS file. Make sure give each `strong` tag a proper class as well, like `price` or `pricing`.

**Comment by bradrgall** [comment]
Gotcha, I knew inline wasn't the proper form but didn't even think of putting a selector on the strong.
