### ISSUE TITLE
Local files

### ISSUE THREAD

**Issue by ghost** [bradrgall/prj-rev-bwfs-dasmoto#4]
https://github.com/bradrgall/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

Consider downloading the images and then writing a relative file path to them in the `img` tags. It's better to not depend on a URL that can break or just otherwise make your images unavailable.

Even better if you stored them in their own `images` folder. This will make your project folder much more organized and maintainable.

**Comment by bradrgall** [comment]
understood.
