### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [bradrgall/prj-rev-bwfs-dasmoto#6]
https://github.com/bradrgall/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L1-L22

You've got a lot of repetition here. You shouldn't have to specify the `font-weight` and the `font-family` in every CSS rule. Write your shared styles into CSS rules with multiple selectors, or with very general selectors like `*`.

https://github.com/bradrgall/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L23

Make sure to watch out for typos.

**Comment by bradrgall** [comment]
undetrstood.
